from app.core.constants import (
    ORDER_CREATED_EVENT,
    ORDER_DELIVERED_EVENT,
    ORDER_PAYMENT_FAILED_EVENT,
    ORDER_PAYMENT_SUCCEEDED_EVENT,
    ORDERS_TOPIC,
    PRODUCT_CREATED_EVENT,
    PRODUCTS_TOPIC,
)

CONSUMER_TOPICS: tuple[str, ...] = (ORDERS_TOPIC, PRODUCTS_TOPIC)

__all__ = [
    "CONSUMER_TOPICS",
    "ORDERS_TOPIC",
    "ORDER_CREATED_EVENT",
    "ORDER_DELIVERED_EVENT",
    "ORDER_PAYMENT_FAILED_EVENT",
    "ORDER_PAYMENT_SUCCEEDED_EVENT",
    "PRODUCTS_TOPIC",
    "PRODUCT_CREATED_EVENT",
]
