REQUEST_ID_HEADER = "X-Request-ID"

DEFAULT_PAGE_LIMIT = 20
MAX_PAGE_LIMIT = 100
DEFAULT_PAGE_OFFSET = 0

DEFAULT_CURRENCY = "ILS"
MAX_CART_ITEM_QUANTITY = 100
PAYMENT_PROVIDER_STUB = "stub"
DELIVERY_PROVIDER_STUB = "stub"

ORDERS_TOPIC = "shekel.orders"
ORDER_CREATED_EVENT = "order_created"
ORDER_PAYMENT_SUCCEEDED_EVENT = "order_payment_succeeded"
ORDER_PAYMENT_FAILED_EVENT = "order_payment_failed"
ORDER_DELIVERED_EVENT = "order_delivered"

PRODUCTS_TOPIC = "shekel.products"
PRODUCT_CREATED_EVENT = "product_created"
DEFAULT_SEED_STOCK = 100
